name: tmtt
description: TMTT

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  font_awesome_flutter:

  # instagram integration.
  flutter_insta: ^1.0.1

  #getX
  get: ^4.6.5

  #intent
  android_intent_plus: ^3.1.1+1

  # Firebase
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.1.0

  http: ^0.13.3
  shimmer: ^2.0.0
  flutter_svg: ^1.1.1+1
  flutter_secure_storage: ^5.0.2
  logger: ^1.1.0
  firebase_analytics: ^9.3.5
  firebase_app_check: ^0.0.7+1
  url_strategy: ^0.2.0
  social_share: ^2.2.1
  image_picker: ^0.8.5+3
  flutter_social_content_share: ^1.0.2
  loopi_share: ^0.0.4
  uuid: ^3.0.6
  carrier_info_v3: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  build_test: ^2.1.0
  build_web_compilers: ^3.0.0
  json_serializable: ^6.3.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Notosans
      fonts:
        - asset: assets/fonts/notosanscjkkr_l.otf
          weight: 300
        - asset: assets/fonts/notosanscjkkr_r.otf
          weight: 400
        - asset: assets/fonts/notosanscjkkr_m.otf
          weight: 500
        - asset: assets/fonts/notosanscjkkr_b.otf
          weight: 700